"""adds email to User model

Revision ID: 23525f14e61b
Revises: 04b4d641daa0
Create Date: 2022-05-03 15:48:24.410878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23525f14e61b'
down_revision = '04b4d641daa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
