"""adds bio & profile_pic_path to User model

Revision ID: 836bdf7686cc
Revises: 23525f14e61b
Create Date: 2022-05-03 23:06:25.027589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836bdf7686cc'
down_revision = '23525f14e61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
